name: qml-course
channels:
    - conda-forge
dependencies:
    - sympy
    - python=3.10
    - pip
    - pip:
          - pennylane
          - jupyterlab
          - numpy==1.23.5
          - matplotlib
          - pylatexenc
          - pandas
          - networkx
          - seaborn
          - qiskit-aer
          - qiskit==1.2.4
          - JLDracula
          - Jinja2
          - tensorflow
          - markupsafe
          - pyyaml
          - tensorflow-datasets
          - Pillow
          - scikit-learn

platforms:
    - linux-64
