name: qml-course
channels:
  - conda-forge
dependencies:
  - pennylane-lightning-gpu
  - python=3.10
  - pip
  - pip:
    - jupyterlab
    - numpy==1.23.5
    - matplotlib
    - pylatexenc
    - pandas
    - networkx
platforms:
  - linux-64
