name: qml-course
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pennylane
    - jupyterlab
    - numpy==1.23.5
    - matplotlib
    - pylatexenc
    - pandas
    - networkx
    - seaborn
    - qiskit-aer
    - qiskit==1.2.4
    - qiskit-machine-learning
    - JLDracula
    - Jinja2
    - tensorflow
    - markupsafe
    - pyyaml
    - tensorflow-datasets
    - Pillow
platforms:
  - linux-64
