name: qml-course
channels:
  - conda-forge
  - pytorch
dependencies:
  - pytorch
  - cpuonly
  - python=3.10
  - pip
  - pip:
    - pennylane
    - jupyterlab
    - numpy==1.23.5
    - matplotlib
    - pylatexenc
    - pandas
    - networkx
    - kaggle
    - scikit-learn
    - seaborn
    - Pillow
    - qiskit-aer
    - qiskit==1.2.4
    - qiskit-machine-learning
    - JLDracula
    - tqdm
platforms:
  - linux-64
